### ISSUE TITLE
디펜던시 버전관리를 gradle.properties 대신에 버전 카달로그 TOML 파일로 변경해보기!

### ISSUE THREAD

**Issue by fp024** [fp024/spring-5-recipes-study#23]
> *  https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

오랜만에 `gradle init` 으로 테스트 프로젝트를 만들어봤는데, 버전관리가 특이하게 되어있다.

* `${projectDir}/gradle/libs.versions.toml`
  ```toml
  # This file was generated by the Gradle 'init' task.
  # https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
  
  [versions]
  junit-jupiter = "5.10.1"
  
  [libraries]
  junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }  
  ```

* `${projectDir}/build.gradle` 의 디펜던시 설정 부분
  ```groovy
  ...
  dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  }
  ...
  ```

`libs.versions.toml` 파일에다 그것을 가져다 쓰는 방식 같은데. 왠지 이렇게 사용을 하게되면 정리가 잘 될 것 같다.

이 변경은 천천히 해보자.. 😅👍
