### ISSUE TITLE
thymeleaf-extras-java8time 확장 모듈은 Thymeleaf 3.1 부터 코어에 포함되서 별도 추가할 필요가 없음

### ISSUE THREAD

**Issue by fp024** [fp024/spring-5-recipes-study#24]
thymeleaf-extras-java8time 확장 모듈은 Thymeleaf 3.1 부터 코어에 포함되서 별도 추가할 필요가 없음

* https://www.thymeleaf.org/doc/articles/thymeleaf31whatsnew.html
> ## 1. 4 Core support for the java.time package
> The `thymeleaf-extras-java8time` extras module has been integrated into the Thymeleaf core: the #temporals expression utility object is now always available.

## TODO

- [ ] 모든 하위 에제에서 제거 하도록 하자!

* toml
  ```toml
  # https://mvnrepository.com/artifact/org.thymeleaf.extras/thymeleaf-extras-java8time
  thymeleaf-extras-java8time = "3.0.4.RELEASE"
  # ...
  thymeleaf-extras-java8time = { module = "org.thymeleaf.extras:thymeleaf-extras-java8time", version.ref = "thymeleaf-extras-java8time" }
  ```

* biuld.gradle
  ```groovy
  implementation (libs.thymeleaf.extras.java8time)
  ```

* config
  ```java
  import org.thymeleaf.extras.java8time.dialect.Java8TimeDialect;
  ...
  templateEngine.addDialect(new Java8TimeDialect());
  ```
